// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYGhQs5wrF9u-EJVDZ8clvv2c3pT6OWpU',
    appId: '1:896658138763:web:01f6947612f7605eb5d68e',
    messagingSenderId: '896658138763',
    projectId: 'flutter-authfirebase',
    authDomain: 'flutter-authfirebase.firebaseapp.com',
    storageBucket: 'flutter-authfirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIwTIEWxltyh5lFs2Ej6BozrxySnNTl-M',
    appId: '1:896658138763:android:b8c7e40101fb6b9bb5d68e',
    messagingSenderId: '896658138763',
    projectId: 'flutter-authfirebase',
    storageBucket: 'flutter-authfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0bk_W-6yF_a1Pif6cnN9ZNz5WTrznST0',
    appId: '1:896658138763:ios:8819efcca208e7cab5d68e',
    messagingSenderId: '896658138763',
    projectId: 'flutter-authfirebase',
    storageBucket: 'flutter-authfirebase.appspot.com',
    iosClientId: '896658138763-rlsja161up078igo7vdtkhmu1bka7qm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0bk_W-6yF_a1Pif6cnN9ZNz5WTrznST0',
    appId: '1:896658138763:ios:8819efcca208e7cab5d68e',
    messagingSenderId: '896658138763',
    projectId: 'flutter-authfirebase',
    storageBucket: 'flutter-authfirebase.appspot.com',
    iosClientId: '896658138763-rlsja161up078igo7vdtkhmu1bka7qm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthfirebase',
  );
}
